name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git for GitHub Pages
        run: |
          git config --global user.email "yadavangad100@gmail.com"
          git config --global user.name "yadav-angad"  

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./host/dist
