name: Build and Deploy to GitHub Pages
on:
 push:
   branches:
     - main
jobs:
 build-deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v3
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
         node-version: 20
     - name: Install dependencies
       run: yarn install
     - name: Build all packages
       run: yarn build
     - name: Configure Git for GitHub Pages
       run: |
          git config --global user.email "yadavangad100@gmail.com"
          git config --global user.name "yadav-angad"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}   
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v4
       with:
         github_token: ${{ secrets.GH_TOKEN }}
         publish_dir: ./dist
         publish_branch: gh-pages