name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install
      - run: chmod +x deploy.sh

      - run: yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
